// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlLkSLmSts9Iz5vz2m-xdbJeb28eoIvQ',
    appId: '1:782392675006:web:1287c459e8a0373e96acef',
    messagingSenderId: '782392675006',
    projectId: 'itsa-9af01',
    authDomain: 'itsa-9af01.firebaseapp.com',
    databaseURL: 'https://itsa-9af01-default-rtdb.firebaseio.com',
    storageBucket: 'itsa-9af01.appspot.com',
    measurementId: 'G-3JJYZG7XWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEAiP1nkFWLpDCWcEe-HUO_xMB2OXVPE',
    appId: '1:782392675006:android:d512f5e3fed2d2cb96acef',
    messagingSenderId: '782392675006',
    projectId: 'itsa-9af01',
    databaseURL: 'https://itsa-9af01-default-rtdb.firebaseio.com',
    storageBucket: 'itsa-9af01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvZemC8bZsxO9LJr3yEk5yrZ8IqxjkfM',
    appId: '1:782392675006:ios:ec4bd46d6029b3b296acef',
    messagingSenderId: '782392675006',
    projectId: 'itsa-9af01',
    databaseURL: 'https://itsa-9af01-default-rtdb.firebaseio.com',
    storageBucket: 'itsa-9af01.appspot.com',
    androidClientId: '782392675006-8ps3sp95q7amadoeppvkfqm96tknig0s.apps.googleusercontent.com',
    iosClientId: '782392675006-2vsfaiaoauajor25omb7c3hb17fuuamh.apps.googleusercontent.com',
    iosBundleId: 'com.example.itsaFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvZemC8bZsxO9LJr3yEk5yrZ8IqxjkfM',
    appId: '1:782392675006:ios:ec4bd46d6029b3b296acef',
    messagingSenderId: '782392675006',
    projectId: 'itsa-9af01',
    databaseURL: 'https://itsa-9af01-default-rtdb.firebaseio.com',
    storageBucket: 'itsa-9af01.appspot.com',
    androidClientId: '782392675006-8ps3sp95q7amadoeppvkfqm96tknig0s.apps.googleusercontent.com',
    iosClientId: '782392675006-2vsfaiaoauajor25omb7c3hb17fuuamh.apps.googleusercontent.com',
    iosBundleId: 'com.example.itsaFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlLkSLmSts9Iz5vz2m-xdbJeb28eoIvQ',
    appId: '1:782392675006:web:6854fab173d9b19396acef',
    messagingSenderId: '782392675006',
    projectId: 'itsa-9af01',
    authDomain: 'itsa-9af01.firebaseapp.com',
    databaseURL: 'https://itsa-9af01-default-rtdb.firebaseio.com',
    storageBucket: 'itsa-9af01.appspot.com',
    measurementId: 'G-RE2WDR8KMH',
  );

}